sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 1.3
    max_update_rate: 0.4
    padding_offset: 0.1
    padding_scale: 1.0
    point_cloud_topic: /ur5/stereo_camera/points2
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#sensors:
#  []
